site_name: Dotfiles
nav:
    - Home: index.md
theme:
    logo: assets/logo-lsai.png
    name: material
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    icon:
    repo: fontawesome/brands/git-alt
    plugins:
     - git-revision-date:
       enabled_if_env: CI
